FROM ubuntu:latest AS build

ENV DEBIAN_FRONTEND=noninteractive

# apt-get update && apt-get upgrade && \
#     apt-get -y --no-install-recommends install

# apk update && apk upgrade &&\
#     apk add --no-cache \

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get -y --no-install-recommends install \
    ca-certificates \
    perl-base \
    # bwa \
    git \
    # perl-doc \
    build-essential
# rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/josephryan/JFR-PerlModules.git

WORKDIR /JFR-PerlModules

RUN perl Makefile.PL && \
    make && \
    make test && \
    make install

WORKDIR /
# RUN rm -rf /JFR-PerlModules

RUN git clone https://github.com/josephryan/FastqSifter.git

WORKDIR /FastqSifter
RUN perl Makefile.PL && \
    make && \
    make install

# RUN rm -rf /FastqSifter

# Final stage: copy only necessary parts (without repo)
FROM ubuntu:latest

RUN apt-get -y update && apt-get -y upgrade && \
    apt install -y bwa \
    perl-doc
COPY --from=build /usr/local/share/man /usr/local/share/man
COPY --from=build /usr/local/share/perl /usr/local/share/perl
COPY --from=build /usr/local/bin/FastqSifter /usr/local/bin/

CMD ["FastqSifter", "--help"]